project_id = "ymddfsjvaxjpvrpuokgo"

[functions.chat]
verify_jwt = false

[functions.shopify-webhook]
verify_jwt = false

[functions.analytics-chat]
verify_jwt = false

[functions.site-recommendations]
verify_jwt = false

[functions.sync-shopify-orders]
verify_jwt = false
